version: '3.5'

services:
  postgres_source:
    container_name: postgres-source
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      PGDATA: /data/postgres
    volumes:
       - postgres-source:/data/postgres
    ports:
      - "5431:5432"

  postgres_target:
    container_name: postgres-target
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      PGDATA: /data/postgres
    volumes:
       - postgres-target:/data/postgres
    ports:
      - "5433:5432"
volumes:
  postgres-source: {}
  postgres-target: {}
